version: "3.8"

services:
  # Nginx for Backend
  nginx-backend:
    image: nginx
    container_name: prestabanconginxbackend-container
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./backend.conf:/etc/nginx/nginx.conf
    networks:
      - prestabancobackend-network
    depends_on:
      - spring1
      - spring2
      - spring3

  # Nginx for Frontend
  nginx-frontend:
    image: nginx
    container_name: prestabanconginxfrontend-container
    restart: always
    ports:
      - "8070:8070"
    volumes:
      - ./frontend.conf:/etc/nginx/nginx.conf
    networks:
      - prestabancofrontend-network
    depends_on:
      - react1
      - react2
      - react3

  # MySQL Database
  mysql:
    container_name: prestabanco-mysql-container
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: prestabancotingeso
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - prestabancotingeso-volume:/var/lib/mysql
    networks:
      - prestabancobackend-network
    deploy:
      restart_policy:
        condition: on-failure

  # Backend services
  spring1:
    container_name: prestabancobackend-container1
    image: alanberrios/prestabancobackend-image
    ports:
      - "8091:8091"
    environment:
      DB_HOST: mysql
      DB_NAME: prestabancotingeso
      DB_PORT: 3306
      DB_USERNAME: mysql
      DB_PASSWORD: 1234
    networks:
      - prestabancobackend-network
    depends_on:
      - mysql
    deploy:
      restart_policy:
        condition: on-failure

  spring2:
    container_name: prestabancobackend-container2
    image: alanberrios/prestabancobackend-image
    ports:
      - "8092:8091"
    environment:
      DB_HOST: mysql
      DB_NAME: prestabancotingeso
      DB_PORT: 3306
      DB_USERNAME: mysql
      DB_PASSWORD: 1234
    networks:
      - prestabancobackend-network
    depends_on:
      - mysql
    deploy:
      restart_policy:
        condition: on-failure

  spring3:
    container_name: prestabancobackend-container3
    image: alanberrios/prestabancobackend-image
    ports:
      - "8093:8091"
    environment:
      DB_HOST: mysql
      DB_NAME: prestabancotingeso
      DB_PORT: 3306
      DB_USERNAME: mysql
      DB_PASSWORD: 1234
    networks:
      - prestabancobackend-network
    depends_on:
      - mysql
    deploy:
      restart_policy:
        condition: on-failure

  # Frontend services
  react1:
    container_name: prestabancofrontend-container1
    image: alanberrios/prestabancofrontend-image
    ports:
      - "3001:3000"
    networks:
      - prestabancofrontend-network
    deploy:
      restart_policy:
        condition: on-failure

  react2:
    container_name: prestabancofrontend-container2
    image: alanberrios/prestabancofrontend-image
    ports:
      - "3002:3000"
    networks:
      - prestabancofrontend-network
    deploy:
      restart_policy:
        condition: on-failure

  react3:
    container_name: prestabancofrontend-container3
    image: alanberrios/prestabancofrontend-image
    ports:
      - "3003:3000"
    networks:
      - prestabancofrontend-network
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  prestabancotingeso-volume:

networks:
  prestabancobackend-network:
  prestabancofrontend-network:
